seed: 42

data:
  data_dir: data/raw
  station_glob: E*.csv
  # Optional JSON with station coordinates (for HybridLocLSTM).
  station_geo_path: null
  datetime_col: datetime
  features: [station, PM10, PM2.5, temperature, rain, pressure, precipitation, wind_speed, clouds, wind_direction]
  never_mask_features: [station]
  target_features: [PM10, PM2.5, temperature, rain, pressure, precipitation, wind_speed, clouds, wind_direction]

experiment:
  history_length: 24
  forecast_horizon: 1
  step_size: 1

  # Train on the first year of data; evaluate on the remaining period (>1 year).
  train_months: 12

  # For the reduced-data stations in 5-fold, remove first 6 months from their training slice.
  reduced_months: 6

  # Two experiment families.
  run_standard: true
  run_five_fold: false
  # Models to compare in both standard and five_fold scenarios.
  models: [transformer, lstm, gru, hybrid_loclstm]
  # Approaches to run per model.
  scopes: [global, per_station]
  n_folds: 5
  # If true, run five-fold only when global model is comparable/better on standard scenario.
  run_five_fold_if_global_not_worse: true
  gate_model: transformer
  gate_metric: mae
  gate_tolerance_pct: 2.0

  # Validation split inside each training slice.
  val_ratio: 0.1

metrics:
  # MAPE is unstable near zero targets (rain etc.). Keep epsilon for zero-filtering
  # and floor the denominator for small non-zero values.
  mape_eps: 0.000001
  mape_min_abs_target: 1.0

models:
  shared:
    # Train-time masking on input windows.
    # Options: none | off | random
    train_mask_mode: random
    train_missing_rate: 0.20

    # Runtime/optimization shared across architectures.
    bias: true
    use_torch_compile: true
    compile_mode: reduce-overhead
    compile_dynamic: false
    optimizer_fused: true
    optimizer_weight_decay: 0.01
    scheduler_warmup_ratio: 0.125
    scheduler_warmup_start_factor: 0.3
    scheduler_min_lr: 0.0000001
    grad_clip_norm: 0.5
    dataloader_num_workers: -1
    dataloader_prefetch_factor: 4
    dataloader_persistent_workers: true
    dataloader_pin_memory: true

  transformer:
    type: transformer
    params:
      d_model: 128
      n_layer: 3
      n_head: 4
      d_ffn: null
      ff_multiplier: 4
      d_k: null
      d_v: null
      diagonal_attention_mask: true
      dropout: 0.1
      norm_eps: 0.000001

  lstm:
    type: lstm
    params:
      hidden_size: 96
      num_layers: 2
      dropout: 0.1

  gru:
    type: gru
    params:
      hidden_size: 96
      num_layers: 2
      dropout: 0.1

  hybrid_loclstm:
    type: hybrid_loclstm
    params:
      hidden_size: 96
      num_layers: 2
      dropout: 0.1
      embed_dim: 16
      geo_dim: 2
      station_feature_index: 0

training:
  device: auto
  epochs: 120
  batch_size: 128
  lr: 0.0008

  early_stopping: true
  patience: 20
  min_delta: 0.0001
  log_every: 5

output:
  save_models: true

tracking:
  enabled: false
  dataset_name: air_quality
  repo_owner: null
  repo_name: null

paths:
  reports_dir: reports/forecast_experiments
  models_dir: artifacts/models/forecast_experiments
  metrics_path: reports/metrics/forecast_metrics.json

hydra:
  run:
    dir: .
  output_subdir: null
